name: Incident Response Workflow

on:
  workflow_dispatch:
  repository_dispatch:
    types: [incident]

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Incident Issue
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "New Incident Detected",
              body: "An incident was detected by the AI Chatbot.",
              labels: ["incident"]
            });
